---
comments: false
---

# Setup

This document details how to create a local copy of this pub's codebase, setup your compute environment, and reproduce the pub itself. This will enable you to experiment with the analysis in the pub and, optionally, contribute revisions to it.

## Obtain local copy

The codebase is hosted on GitHub and can be found [here](https://github.com/{{< var pub.org >}}/{{< var pub.repo >}}).

To obtain a local copy of this repo, you can either *clone* it directly or fork it to your own GitHub account, then clone your fork. If you aren't sure what's best, our suggestion is to clone directly unless you both (1) want to propose a revision for the publication and (2) are not an employee of Arcadia Science.

To clone:

```bash
git clone https://github.com/{{< var pub.org >}}/{{< var pub.repo >}}.git
```

## Installation

::: {.callout-important}
The publication is rendered with [Quarto](https://quarto.org/). If you don't have it installed (check with `quarto --version`), you can install it [here](https://quarto.org/docs/get-started/).
:::

This repository uses conda to manage the computational and build environment. If you don't have it installed (check with `conda --version`), you can find operating system-specific instructions for installing miniconda [here](https://docs.conda.io/projects/miniconda/en/latest/). After installing, run the following commands to create and activate the environment.

```bash
conda env create -n {{< var pub.repo >}} --file env.yml
conda activate {{< var pub.repo >}}
```

Now, install any internal packages in the repository:

```bash
pip install -e .
```

And finally, if you plan to submit a pull request, install the [pre-commit](https://pre-commit.com/) hooks:

```bash
pre-commit install
```

# What's next?

With a copy of the code and compute environment set up on your local machine, you can now reproduce or modify a local copy of the publication however you see fit. Read on to get started.

## Reproduce

The best way to ensure you've correctly set up your code and compute environment is to reproduce this work. Fortunately, the analysis, and therefore the publication itself, can be reproduced with the following command:

```bash
make execute
```

(Make sure you're in the conda environment you created above)

This will execute and render the notebook `index.ipynb`, then build the publication site. To preview the site, use

```bash
make preview
```

This will open a local instance of the publication in your default browser.

## Modify

To modify or extend any analyses, open up `index.ipynb` with Jupyter or your favorite IDE. To preview changes as you modify the notebook, run `make preview` again and leave the command running. As you make changes to the notebook, the preview site will automatically reload.

## Publish

If you've improved the publication, consider contributing so we can update the hosted publication with your edits (big or small!). To get started, see our [contributing guide](CONTRIBUTING.qmd).
